import json
from pathlib import Path

import pytest


FIXTURES = Path(__file__).parent / "fixtures" / "publish"


def publisher_entry(tmp_path=None, **source_overrides):
    sources = {
        "skill_file": str(FIXTURES / "SKILL.md"),
        "results": str(FIXTURES / "RESULTS.md"),
        "cases": str(FIXTURES / "cases.jsonl"),
        "forge": str(FIXTURES / "forge-results.json"),
    }
    sources.update(source_overrides)
    return {
        "skill": "highsignal",
        "category": "writing",
        "canonical_repo": "https://github.com/jpvarbed/highsignal",
        "sources": sources,
    }


def make_repo(tmp_path, readme=None):
    root = tmp_path / "skills-repo"
    skill_names = [
        ("analysis", "csv-analysis"),
        ("analysis", "json-output"),
        ("analysis", "data-cleanup"),
        ("analysis", "reporting"),
        ("analysis", "chart-review"),
        ("writing", "draft-edit"),
        ("writing", "hook-writing"),
        ("writing", "style-cleanup"),
        ("code", "code-review"),
        ("code", "test-design"),
    ]
    for category, skill in skill_names:
        path = root / category / skill
        path.mkdir(parents=True)
        (path / "SKILL.md").write_text(f"# {skill}\n\nFixture skill.\n")
    (root / ".hidden").mkdir()
    (root / ".hidden" / "ignored").mkdir()
    (root / ".hidden" / "ignored" / "SKILL.md").write_text("hidden\n")
    (root / "README.md").write_text(readme or "# Public Skills\n\nIntro.\n\n## Skills\n\nExisting list.\n")
    return root


def tree_bytes(root):
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def run_publish(root, publishers=None, **kwargs):
    import publish

    return publish.run_publish(root, publishers=publishers or [publisher_entry()], **kwargs)


def test_measured_render_uses_fixture_values_and_adds_eleventh_skill(tmp_path):
    root = make_repo(tmp_path)

    assert run_publish(root) == 0

    perf = (root / "writing" / "highsignal" / "PERF.md").read_text()
    readme = (root / "README.md").read_text()
    data = json.loads((root / "writing" / "highsignal" / "eval" / "data.json").read_text())

    assert "<!-- canonical: https://github.com/jpvarbed/highsignal; curated copy -->" in (
        root / "writing" / "highsignal" / "SKILL.md"
    ).read_text()
    assert "Detection benchmark: highsignal detect eval (N=4; k=1 single run" in perf
    assert "| `codex exec` (codex-cli 0.142.4, default model) | 13/14 | 93% | 0 |" in perf
    assert "| haiku | 11/19 (57.9%) | v1 9/19 (47.4%) | -10.5pp |" in perf
    assert "| openai | 10/19 (52.6%) | v2 12/19 (63.2%) | +10.5pp |" in perf
    assert "Regressions are shown explicitly; negative lift means the best variant scored below the original." in perf
    assert "Generated by arena publish from eval/RESULTS.md, eval/data.json. Do not hand-edit." in perf
    assert "detection `codex exec` (codex-cli 0.142.4, default model) 13/14; openai +10.5pp / haiku -10.5pp pre->post" in readme
    assert readme.count("| [") == 11
    assert data["detection"]["case_count"] == 4
    assert data["forge"]["models"][0]["lift_pp"] == -10.5


def test_measured_render_follows_changed_fixture_value(tmp_path):
    root = make_repo(tmp_path)
    changed = tmp_path / "RESULTS.md"
    changed.write_text((FIXTURES / "RESULTS.md").read_text().replace("13/14 | 93%", "14/14 | 100%"))

    assert run_publish(root, publishers=[publisher_entry(results=str(changed))]) == 0

    perf = (root / "writing" / "highsignal" / "PERF.md").read_text()
    readme = (root / "README.md").read_text()
    assert "14/14 | 100%" in perf
    assert "14/14; openai +10.5pp" in readme


def test_unmeasured_render_present_for_existing_skills(tmp_path):
    root = make_repo(tmp_path)

    assert run_publish(root) == 0

    perf = (root / "analysis" / "csv-analysis" / "PERF.md").read_text()
    assert "No objective eval yet." in perf
    assert "Numbers appear here when this skill gets a benchmark; see the methodology page." in perf


def test_readme_block_created_and_rest_untouched(tmp_path):
    root = make_repo(tmp_path, "# Public Skills\n\nIntro stays.\n\n## Skills\n\nExisting list stays.\n")

    assert run_publish(root) == 0

    readme = (root / "README.md").read_text()
    assert readme.startswith("# Public Skills\n\nIntro stays.\n\n<!-- arena-publish:begin -->")
    assert readme.endswith("## Skills\n\nExisting list stays.\n")


def test_readme_block_replaced_in_place(tmp_path):
    root = make_repo(
        tmp_path,
        "# Public Skills\n\nBefore.\n\n<!-- arena-publish:begin -->\nold block\n<!-- arena-publish:end -->\n\nAfter.\n",
    )

    assert run_publish(root) == 0

    readme = (root / "README.md").read_text()
    assert "old block" not in readme
    assert readme.startswith("# Public Skills\n\nBefore.\n\n<!-- arena-publish:begin -->")
    assert readme.endswith("\n\nAfter.\n")


@pytest.mark.parametrize(
    "readme",
    [
        "<!-- arena-publish:begin -->\none\n<!-- arena-publish:begin -->\ntwo\n<!-- arena-publish:end -->\n",
        "<!-- arena-publish:end -->\nwrong\n<!-- arena-publish:begin -->\n",
        "<!-- arena-publish:begin -->\nmissing end\n",
    ],
)
def test_readme_marker_errors_fail_closed(tmp_path, readme):
    root = make_repo(tmp_path, readme)
    before = tree_bytes(root)

    assert run_publish(root) == 1

    assert tree_bytes(root) == before


def test_idempotency_run_twice_byte_identical(tmp_path):
    root = make_repo(tmp_path)

    assert run_publish(root) == 0
    first = tree_bytes(root)
    assert run_publish(root) == 0

    assert tree_bytes(root) == first


def test_missing_evidence_source_renders_skip_note_and_exits_zero(tmp_path):
    root = make_repo(tmp_path)

    assert run_publish(root, publishers=[publisher_entry(results=str(tmp_path / "missing.md"))]) == 0

    perf = (root / "writing" / "highsignal" / "PERF.md").read_text()
    assert "- detection results source missing; skipped." in perf
    assert "Forge pre/post" in perf


@pytest.mark.parametrize(
    "planted",
    [
        "/Users/private/source",
        "~" + "/dev/private-source",
        "dev" + "/notes/private.md",
        "TASK-123",
        "sk-" + ("a" * 24),
    ],
)
def test_hygiene_tripwire_scans_rendered_tree(tmp_path, planted):
    root = make_repo(tmp_path)
    dirty_skill = tmp_path / "dirty-SKILL.md"
    dirty_skill.write_text((FIXTURES / "SKILL.md").read_text() + "\n" + planted + "\n")

    assert run_publish(root, publishers=[publisher_entry(skill_file=str(dirty_skill))]) == 1


def test_dry_run_prints_planned_writes_and_touches_nothing(tmp_path, capsys):
    root = make_repo(tmp_path)
    before = tree_bytes(root)

    assert run_publish(root, dry_run=True) == 0

    out = capsys.readouterr().out
    assert "would write README.md" in out
    assert "would write writing/highsignal/PERF.md" in out
    assert tree_bytes(root) == before


def test_verify_passes_after_publish_and_fails_on_tampered_number(tmp_path):
    import publish

    root = make_repo(tmp_path)
    assert run_publish(root) == 0
    assert publish.run_verify(root) == 0

    perf_path = root / "writing" / "highsignal" / "PERF.md"
    perf_path.write_text(perf_path.read_text().replace("+10.5pp", "+99.9pp", 1))

    assert publish.run_verify(root) == 1


def test_arena_publish_cli_path(tmp_path):
    import arena

    root = make_repo(tmp_path)

    assert arena.main(["publish", "--skills-repo", str(root), "--dry-run"]) == 0


def test_verify_writes_acceptance_report(tmp_path):
    import publish as publish_mod

    repo = make_repo(tmp_path)
    publish_mod.run_publish(repo)
    report = tmp_path / "verification.md"
    assert publish_mod.run_verify(repo, report_path=report) == 0
    text = report.read_text()
    assert "Publish verification record" in text
    assert "| yes |" in text
