import json
from pathlib import Path

import pytest


FIXTURES = Path(__file__).parent / "fixtures" / "publish"


def publisher_entry(tmp_path=None, **source_overrides):
    sources = {
        "skill_file": str(FIXTURES / "SKILL.md"),
        "results": str(FIXTURES / "RESULTS.md"),
        "cases": str(FIXTURES / "cases.jsonl"),
        "forge": str(FIXTURES / "forge-results.json"),
    }
    sources.update(source_overrides)
    return {
        "skill": "highsignal",
        "category": "writing",
        "canonical_repo": "https://github.com/jpvarbed/highsignal",
        "sources": sources,
    }


def make_repo(tmp_path, readme=None):
    root = tmp_path / "skills-repo"
    skill_names = [
        ("analysis", "csv-analysis"),
        ("analysis", "json-output"),
        ("analysis", "data-cleanup"),
        ("analysis", "reporting"),
        ("analysis", "chart-review"),
        ("writing", "draft-edit"),
        ("writing", "hook-writing"),
        ("writing", "style-cleanup"),
        ("code", "code-review"),
        ("code", "test-design"),
    ]
    for category, skill in skill_names:
        path = root / category / skill
        path.mkdir(parents=True)
        (path / "SKILL.md").write_text(f"# {skill}\n\nFixture skill.\n")
    (root / ".hidden").mkdir()
    (root / ".hidden" / "ignored").mkdir()
    (root / ".hidden" / "ignored" / "SKILL.md").write_text("hidden\n")
    (root / "README.md").write_text(readme or "# Public Skills\n\nIntro.\n\n## Skills\n\nExisting list.\n")
    return root


REQUESTED_PERF_PATHS = {
    "meta/goal-spec/PERF.md",
    "meta/instruction-conflicts/PERF.md",
    "meta/apply-paper/PERF.md",
    "meta/determinize-refactor/PERF.md",
    "productivity/caveman/PERF.md",
    "review/adversarial-review/PERF.md",
    "review/gtm-diligence/PERF.md",
    "review/visual-critique/PERF.md",
    "writing/highsignal/PERF.md",
    "writing/writing-hooks/PERF.md",
    "engineering/total-tdd/PERF.md",
}


def requested_publishers_without_evidence():
    import publish

    return [
        {
            "skill": entry["skill"],
            "category": entry["category"],
            "canonical_repo": entry.get("canonical_repo", "https://github.com/jpvarbed/skill-arena"),
            "sources": {},
        }
        for entry in publish.PUBLISHERS
        if f"{entry['category']}/{entry['skill']}/PERF.md" in REQUESTED_PERF_PATHS
    ]


def make_requested_perf_repo(tmp_path):
    root = tmp_path / "skills-repo"
    for rel_path in REQUESTED_PERF_PATHS:
        skill_dir = root / Path(rel_path).parent
        skill_dir.mkdir(parents=True, exist_ok=True)
        (skill_dir / "SKILL.md").write_text(f"# {skill_dir.name}\n\nFixture skill.\n")
    (root / "README.md").write_text("# Public Skills\n\n## Skills\n")
    return root


def tree_bytes(root):
    return {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def run_publish(root, publishers=None, **kwargs):
    import publish

    return publish.run_publish(root, publishers=publishers or [publisher_entry()], **kwargs)


def test_measured_render_uses_fixture_values_and_adds_eleventh_skill(tmp_path):
    root = make_repo(tmp_path)

    assert run_publish(root) == 0

    perf = (root / "writing" / "highsignal" / "PERF.md").read_text()
    readme = (root / "README.md").read_text()
    data = json.loads((root / "writing" / "highsignal" / "eval" / "data.json").read_text())

    assert "<!-- canonical: https://github.com/jpvarbed/highsignal; curated copy -->" in (
        root / "writing" / "highsignal" / "SKILL.md"
    ).read_text()
    assert "Detection benchmark: highsignal detect eval (N=4; k=1 single run" in perf
    assert "| `codex exec` (codex-cli 0.142.4, default model) | 13/14 | 93% | 0 |" in perf
    assert "| haiku | 11/19 (57.9%) | v1 9/19 (47.4%) | -10.5pp |" in perf
    assert "| openai | 10/19 (52.6%) | v2 12/19 (63.2%) | +10.5pp |" in perf
    assert "Regressions are shown explicitly; negative lift means the best variant scored below the original." in perf
    assert "Generated by arena publish from eval/RESULTS.md, eval/data.json. Do not hand-edit." in perf
    assert "detection `codex exec` (codex-cli 0.142.4, default model) 13/14; openai +10.5pp / haiku -10.5pp pre->post" in readme
    assert readme.count("| [") == 11
    assert data["detection"]["case_count"] == 4
    assert data["forge"]["models"][0]["lift_pp"] == -10.5


def test_measured_render_follows_changed_fixture_value(tmp_path):
    root = make_repo(tmp_path)
    changed = tmp_path / "RESULTS.md"
    changed.write_text((FIXTURES / "RESULTS.md").read_text().replace("13/14 | 93%", "14/14 | 100%"))

    assert run_publish(root, publishers=[publisher_entry(results=str(changed))]) == 0

    perf = (root / "writing" / "highsignal" / "PERF.md").read_text()
    readme = (root / "README.md").read_text()
    assert "14/14 | 100%" in perf
    assert "14/14; openai +10.5pp" in readme


def test_unmeasured_render_present_for_existing_skills(tmp_path):
    root = make_repo(tmp_path)

    assert run_publish(root) == 0

    perf = (root / "analysis" / "csv-analysis" / "PERF.md").read_text()
    assert "No objective eval yet." in perf
    assert "Numbers appear here when this skill gets a benchmark; see the methodology page." in perf


def test_readme_block_created_and_rest_untouched(tmp_path):
    root = make_repo(tmp_path, "# Public Skills\n\nIntro stays.\n\n## Skills\n\nExisting list stays.\n")

    assert run_publish(root) == 0

    readme = (root / "README.md").read_text()
    assert readme.startswith("# Public Skills\n\nIntro stays.\n\n<!-- arena-publish:begin -->")
    assert readme.endswith("## Skills\n\nExisting list stays.\n")


def test_readme_block_replaced_in_place(tmp_path):
    root = make_repo(
        tmp_path,
        "# Public Skills\n\nBefore.\n\n<!-- arena-publish:begin -->\nold block\n<!-- arena-publish:end -->\n\nAfter.\n",
    )

    assert run_publish(root) == 0

    readme = (root / "README.md").read_text()
    assert "old block" not in readme
    assert readme.startswith("# Public Skills\n\nBefore.\n\n<!-- arena-publish:begin -->")
    assert readme.endswith("\n\nAfter.\n")


@pytest.mark.parametrize(
    "readme",
    [
        "<!-- arena-publish:begin -->\none\n<!-- arena-publish:begin -->\ntwo\n<!-- arena-publish:end -->\n",
        "<!-- arena-publish:end -->\nwrong\n<!-- arena-publish:begin -->\n",
        "<!-- arena-publish:begin -->\nmissing end\n",
    ],
)
def test_readme_marker_errors_fail_closed(tmp_path, readme):
    root = make_repo(tmp_path, readme)
    before = tree_bytes(root)

    assert run_publish(root) == 1

    assert tree_bytes(root) == before


def test_idempotency_run_twice_byte_identical(tmp_path):
    root = make_repo(tmp_path)

    assert run_publish(root) == 0
    first = tree_bytes(root)
    assert run_publish(root) == 0

    assert tree_bytes(root) == first


def test_missing_evidence_source_renders_skip_note_and_exits_zero(tmp_path):
    root = make_repo(tmp_path)

    assert run_publish(root, publishers=[publisher_entry(results=str(tmp_path / "missing.md"))]) == 0

    perf = (root / "writing" / "highsignal" / "PERF.md").read_text()
    assert "- detection results source missing; skipped." in perf
    assert "Forge pre/post" in perf


@pytest.mark.parametrize(
    "planted",
    [
        "/Users/private/source",
        "~" + "/dev/private-source",
        "dev" + "/notes/private.md",
        "TASK-123",
        "sk-" + ("a" * 24),
    ],
)
def test_hygiene_tripwire_scans_rendered_tree(tmp_path, planted):
    root = make_repo(tmp_path)
    dirty_skill = tmp_path / "dirty-SKILL.md"
    dirty_skill.write_text((FIXTURES / "SKILL.md").read_text() + "\n" + planted + "\n")

    assert run_publish(root, publishers=[publisher_entry(skill_file=str(dirty_skill))]) == 1


def test_dry_run_prints_planned_writes_and_touches_nothing(tmp_path, capsys):
    root = make_repo(tmp_path)
    before = tree_bytes(root)

    assert run_publish(root, dry_run=True) == 0

    out = capsys.readouterr().out
    assert "would write README.md" in out
    assert "would write writing/highsignal/PERF.md" in out
    assert tree_bytes(root) == before


def test_verify_passes_after_publish_and_fails_on_tampered_number(tmp_path):
    import publish

    root = make_repo(tmp_path)
    assert run_publish(root) == 0
    assert publish.run_verify(root, publishers=[publisher_entry()]) == 0

    perf_path = root / "writing" / "highsignal" / "PERF.md"
    perf_path.write_text(perf_path.read_text().replace("+10.5pp", "+99.9pp", 1))

    assert publish.run_verify(root, publishers=[publisher_entry()]) == 1


def test_arena_publish_cli_path(tmp_path):
    import arena

    root = make_repo(tmp_path)

    assert arena.main(["publish", "--skills-repo", str(root), "--dry-run"]) == 0


def _git_init(repo):
    import subprocess
    for args in (["init", "-q"], ["config", "user.email", "t@t"], ["config", "user.name", "t"],
                 ["add", "-A"], ["commit", "-q", "-m", "init", "--allow-empty"]):
        subprocess.run(["git", "-C", str(repo), *args], check=True, capture_output=True)


def test_verify_writes_acceptance_report(tmp_path):
    import subprocess

    import publish as publish_mod

    repo = make_repo(tmp_path)
    _git_init(repo)
    publish_mod.run_publish(repo)
    subprocess.run(["git", "-C", str(repo), "add", "-A"], check=True, capture_output=True)
    subprocess.run(["git", "-C", str(repo), "commit", "-m", "publish"], check=True, capture_output=True)
    report = tmp_path / "verification.md"
    assert publish_mod.run_verify(repo, report_path=report) == 0
    text = report.read_text()
    assert "Publish verification record" in text
    assert "| yes |" in text
    assert "worktree clean" in text


def test_verify_report_refuses_dirty_tree(tmp_path):
    import pytest

    import publish as publish_mod

    repo = make_repo(tmp_path)
    _git_init(repo)
    publish_mod.run_publish(repo)
    report = tmp_path / "verification.md"
    with pytest.raises(SystemExit):
        publish_mod.run_verify(repo, report_path=report)


def test_default_registry_covers_requested_perf_paths():
    import publish

    registered = {f"{entry['category']}/{entry['skill']}/PERF.md" for entry in publish.PUBLISHERS}

    assert REQUESTED_PERF_PATHS <= registered


def test_requested_perf_surfaces_render_as_honest_stubs_and_are_idempotent(tmp_path):
    root = make_requested_perf_repo(tmp_path)
    publishers = requested_publishers_without_evidence()

    assert run_publish(root, publishers=publishers) == 0
    first = tree_bytes(root)
    assert run_publish(root, publishers=publishers) == 0

    assert tree_bytes(root) == first
    for rel_path in REQUESTED_PERF_PATHS:
        text = (root / rel_path).read_text()
        assert "No objective eval yet." in text
        assert "Generated by arena publish from no objective evidence. Do not hand-edit." in text


def test_arena_results_source_renders_measured_perf_when_evidence_exists(tmp_path):
    root = make_requested_perf_repo(tmp_path)
    results = tmp_path / "results.json"
    cases = tmp_path / "cases.jsonl"
    results.write_text(json.dumps({
        "skills": {
            "instruction-conflicts": {
                "cells": [
                    {
                        "backend": "codex",
                        "prompt_variant": "with-skill",
                        "n": 2,
                        "passes": 2,
                        "pass_rate": 1.0,
                        "cases": [
                            {"id": "dirty", "pass": True, "detail": "expected=['tone-conflict'] got=['tone-conflict']"},
                            {"id": "clean", "pass": True, "detail": "clean"},
                        ],
                    }
                ]
            }
        }
    }))
    cases.write_text(json.dumps({"id": "dirty"}) + "\n" + json.dumps({"id": "clean"}) + "\n")
    publishers = [
        {
            "skill": "instruction-conflicts",
            "category": "meta",
            "canonical_repo": "https://github.com/jpvarbed/skill-arena",
            "sources": {"arena_results": str(results), "cases": str(cases)},
        }
    ]

    assert run_publish(root, publishers=publishers) == 0

    perf = (root / "meta" / "instruction-conflicts" / "PERF.md").read_text()
    assert "Detection benchmark: instruction-conflicts arena eval (N=2; k=1 single run; models: codex / with-skill)." in perf
    assert "| codex / with-skill | 2/2 | 100% | 0 |" in perf


def test_dry_run_arena_results_do_not_render_as_evidence(tmp_path):
    root = make_requested_perf_repo(tmp_path)
    results = tmp_path / "results.json"
    results.write_text(json.dumps({
        "dry_run": True,
        "skills": {
            "caveman": {
                "cells": [
                    {"backend": "codex", "prompt_variant": "with-skill", "n": 1, "passes": 1, "cases": []}
                ]
            }
        },
    }))
    publishers = [
        {
            "skill": "caveman",
            "category": "productivity",
            "canonical_repo": "https://github.com/jpvarbed/skill-arena",
            "sources": {"arena_results": str(results)},
        }
    ]

    assert run_publish(root, publishers=publishers) == 0

    perf = (root / "productivity" / "caveman" / "PERF.md").read_text()
    assert "No objective eval yet." in perf
    assert "arena results are dry-run stubs" in perf and "; skipped." in perf


def test_multi_path_arena_results_merge_rows_with_model_ids(tmp_path):
    root = make_requested_perf_repo(tmp_path)

    def results_file(name, backend, model, passes):
        path = tmp_path / name
        path.write_text(json.dumps({
            "skills": {
                "caveman": {
                    "cells": [
                        {"backend": backend, "model": model, "prompt_variant": "with-skill",
                         "n": 12, "passes": passes, "cases": []}
                    ]
                }
            },
        }))
        return str(path)

    old = results_file("old.json", "codex", None, 6)          # historical: no model id
    new = results_file("new.json", "codex-56sol", "gpt-5.6-sol", 9)
    publishers = [
        {
            "skill": "caveman",
            "category": "productivity",
            "canonical_repo": "https://github.com/jpvarbed/skill-arena",
            "sources": {"arena_results": [old, new, str(tmp_path / "absent.json")]},
        }
    ]

    assert run_publish(root, publishers=publishers) == 0

    perf = (root / "productivity" / "caveman" / "PERF.md").read_text()
    # merged rows, in order; exact model id preferred when the run recorded one
    assert "| codex / with-skill | 6/12 |" in perf
    assert "| gpt-5.6-sol / with-skill | 9/12 |" in perf
    assert "arena results source missing" in perf and "absent.json" in perf


def test_appendix_md_renders_verbatim_and_lands_in_data(tmp_path):
    root = make_requested_perf_repo(tmp_path)
    results = tmp_path / "results.json"
    results.write_text(json.dumps({
        "skills": {
            "caveman": {
                "cells": [
                    {"backend": "codex", "prompt_variant": "with-skill", "n": 2, "passes": 1, "cases": []}
                ]
            }
        },
    }))
    appendix = tmp_path / "precision.md"
    appendix.write_text("## Precision diagnostic (secondary)\n\n| a | b |\n|---|---|\n| 1 | 2 |\n")
    publishers = [
        {
            "skill": "caveman",
            "category": "productivity",
            "canonical_repo": "https://github.com/jpvarbed/skill-arena",
            "sources": {"arena_results": str(results), "appendix_md": str(appendix)},
        }
    ]

    assert run_publish(root, publishers=publishers) == 0

    perf = (root / "productivity" / "caveman" / "PERF.md").read_text()
    assert "## Precision diagnostic (secondary)" in perf
    assert perf.index("## Precision diagnostic") < perf.index("## Caveats")
    data = json.loads((root / "productivity" / "caveman" / "eval" / "data.json").read_text())
    assert data["appendix"].startswith("## Precision diagnostic")


def test_registry_note_renders_with_parser_notes(tmp_path):
    root = make_requested_perf_repo(tmp_path)
    results = tmp_path / "results.json"
    results.write_text(json.dumps({
        "skills": {
            "caveman": {
                "cells": [
                    {"backend": "codex", "prompt_variant": "with-skill", "n": 2, "passes": 1, "cases": []}
                ]
            }
        },
    }))
    publishers = [
        {
            "skill": "caveman",
            "category": "productivity",
            "canonical_repo": "https://github.com/jpvarbed/skill-arena",
            "note": "Shipped SKILL.md is the measured winner.",
            "sources": {"arena_results": str(results)},
        }
    ]

    assert run_publish(root, publishers=publishers) == 0

    perf = (root / "productivity" / "caveman" / "PERF.md").read_text()
    assert "- Shipped SKILL.md is the measured winner." in perf
